// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Version ...
var Version = "dev"

// Copyright ...
var Copyright = "© 2020 - 2026 FloatTech"

// Banner ...
var Banner = "* OneBot + ZeroBot + Golang\n" +
	"* Version " + Version + " - 2026-03-10 17:44:56 +0800 CST\n" +
	"* Copyright " + Copyright + ". All Rights Reserved.\n" +
	"* Project: https://github.com/FloatTech/ZeroBot-Plugin"
